﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace HousesPricesPrediction
{
    public partial class MLModel1
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"SquareMeter", @"SquareMeter"),new InputOutputColumnPair(@"Bedrooms", @"Bedrooms"),new InputOutputColumnPair(@"Bathrooms", @"Bathrooms"),new InputOutputColumnPair(@"Neighborhood", @"Neighborhood"),new InputOutputColumnPair(@"YearBuilt", @"YearBuilt")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"SquareMeter",@"Bedrooms",@"Bathrooms",@"Neighborhood",@"YearBuilt"}))      
                                    .Append(mlContext.Regression.Trainers.FastTree(new FastTreeRegressionTrainer.Options(){NumberOfLeaves=4,MinimumExampleCountPerLeaf=4,NumberOfTrees=664,MaximumBinCountPerFeature=135,FeatureFraction=0.144904734083617,LearningRate=0.121282247102899,LabelColumnName=@"Price",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
